name: CI
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: woryzen
    steps:
      - name: Checkout sources
        uses: https://github.com/RouxAntoine/checkout@v3.5.4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Execute Gradle build
        env:
          PUBLISHER_TOKEN: ${{ secrets.PUBLISHER_TOKEN }}
        run: ./gradlew build publish
